In [5]:
import pandas as pd

In [6]:
#emissionshackmit
#facility name
#parent company name

In [35]:
p_2017 = pd.read_csv('2017_parent_company.csv') 
p_2018 = pd.read_csv('2018_parent_company.csv')
p_2019 = pd.read_csv('2019_parent_company.csv')
p_2020 = pd.read_csv('2020_parent_company.csv')

T_2017 = p_2017[["FACILITY NAME", "PARENT COMPANY NAME", "FACILITY NAICS CODE"]]
T_2018 = p_2018[["FACILITY NAME", "PARENT COMPANY NAME", "FACILITY NAICS CODE"]]
T_2019 = p_2019[["FACILITY NAME", "PARENT COMPANY NAME", "FACILITY NAICS CODE"]]
T_2020 = p_2020[["FACILITY NAME", "PARENT COMPANY NAME", "FACILITY NAICS CODE"]]

de_2017 = pd.read_csv('2017de.csv')
#sf6_2017 = pd.read_csv('2017sf6.csv')
de_2018 = pd.read_csv('2018de.csv')
#sf6_2018 = pd.read_csv('2018sf6.csv')
de_2019 = pd.read_csv('2019de.csv')
#sf6_2019 = pd.read_csv('2019sf6.csv')
de_2020 = pd.read_csv('2020de.csv')
#sf6_2020 = pd.read_csv('2020sf6.csv')

T_de_2017 = de_2017[["Facility Name", "Total reported direct emissions", "CO2 emissions (non-biogenic) ", "Methane (CH4) emissions ", "Nitrous Oxide (N2O) emissions ", "HFC emissions", "PFC emissions", "SF6 emissions ", "NF3 emissions", "Other Fully Fluorinated GHG emissions", "Very Short-lived Compounds emissions", "Other GHGs (metric tons CO2e)", "Biogenic CO2 emissions (metric tons)"]]
#T_sf6_2017 = sf6_2017[["Facility Name", "SF6 emissions "]]
T_de_2018 = de_2018[["Facility Name", "Total reported direct emissions", "CO2 emissions (non-biogenic) ", "Methane (CH4) emissions ", "Nitrous Oxide (N2O) emissions ", "HFC emissions", "PFC emissions", "SF6 emissions ", "NF3 emissions", "Other Fully Fluorinated GHG emissions", "Very Short-lived Compounds emissions", "Other GHGs (metric tons CO2e)", "Biogenic CO2 emissions (metric tons)"]]
#T_sf6_2018 = sf6_2018[["Facility Name", "SF6 emissions "]]
T_de_2019 = de_2019[["Facility Name", "Total reported direct emissions", "CO2 emissions (non-biogenic) ", "Methane (CH4) emissions ", "Nitrous Oxide (N2O) emissions ", "HFC emissions", "PFC emissions", "SF6 emissions ", "NF3 emissions", "Other Fully Fluorinated GHG emissions", "Very Short-lived Compounds emissions", "Other GHGs (metric tons CO2e)", "Biogenic CO2 emissions (metric tons)"]]
#T_sf6_2019 = sf6_2019[["Facility Name", "SF6 emissions "]]
T_de_2020 = de_2020[["Facility Name", "Total reported direct emissions", "CO2 emissions (non-biogenic) ", "Methane (CH4) emissions ", "Nitrous Oxide (N2O) emissions ", "HFC emissions", "PFC emissions", "SF6 emissions ", "NF3 emissions", "Other Fully Fluorinated GHG emissions", "Very Short-lived Compounds emissions", "Other GHGs (metric tons CO2e)", "Biogenic CO2 emissions (metric tons)"]]
#T_sf6_2020 = sf6_2020[["Facility Name", "SF6 emissions "]]

'''

CO2 emissions (non-biogenic) 	Methane (CH4) emissions 	Nitrous Oxide (N2O) emissions 	HFC emissions	PFC emissions	SF6 emissions 	NF3 emissions	Other Fully Fluorinated GHG emissions	HFE emissions	Very Short-lived Compounds emissions	Other GHGs (metric tons CO2e)	Biogenic CO2 emissions (metric tons)


'''

#Final output 
#T_de_20**
#T_20**

'\n\nCO2 emissions (non-biogenic) \tMethane (CH4) emissions \tNitrous Oxide (N2O) emissions \tHFC emissions\tPFC emissions\tSF6 emissions \tNF3 emissions\tOther Fully Fluorinated GHG emissions\tHFE emissions\tVery Short-lived Compounds emissions\tOther GHGs (metric tons CO2e)\tBiogenic CO2 emissions (metric tons)\n\n\n'

In [40]:
T_2017

                        FACILITY NAME PARENT COMPANY NAME  FACILITY NAICS CODE
0     PSE Ferndale Generating Station  PUGET SOUND ENERGY             221112.0
1         Ardagh Glass Inc. (Dunkirk)        ARDAGH GROUP             327213.0
2       Ardagh Glass Inc. (Henderson)        ARDAGH GROUP             327213.0
3         Ardagh Glass Inc. (Lincoln)        ARDAGH GROUP             327213.0
4          Ardagh Glass Inc. (Madera)        ARDAGH GROUP             327213.0
...                               ...                 ...                  ...
9915                              NaN                 NaN                  NaN
9916                              NaN                 NaN                  NaN
9917                              NaN                 NaN                  NaN
9918                              NaN                 NaN                  NaN
9919                              NaN                 NaN                  NaN

[9920 rows x 3 columns]

In [42]:
T_de_2020

,Facility Name,Total reported direct emissions,CO2 emissions (non-biogenic),Methane (CH4) emissions,Nitrous Oxide (N2O) emissions,HFC emissions,PFC emissions,SF6 emissions,NF3 emissions,Other Fully Fluorinated GHG emissions,Very Short-lived Compounds emissions,Other GHGs (metric tons CO2e),Biogenic CO2 emissions (metric tons)
0,121 REGIONAL DISPOSAL FACILITY,"504,064.00",NaN,"504,064.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,23rd and 3rd,"60,819.70","60,751.20",31.25,37.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3Bear Libby Gas Plant,"40,521.81","39,555.50",945.75,20.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,31st Street Landfill,"100,500.95",334.9,"100,165.75",0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3M BROWNWOOD,"29,359.64","29,329.50",13.75,16.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6510,Zider,"22,359.12","22,350.20",4.75,4.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6511,Zion Energy Center,"325,679.42","325,344.10",151.75,183.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6512,Zuni,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6513,voestalpine Texas LLC,"650,907.10","650,879.70",12.5,14.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6514,white oak landfill,"89,476.75",0,"89,476.75",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#merge sf6 with total emissions for each year
#D2017 = T_de_2017.merge(T_sf6_2017, left_on ='Facility Name', right_on='Facility Name') 
#D2018 = T_de_2018.merge(T_sf6_2018, left_on ='Facility Name', right_on='Facility Name') 
#D2019 = T_de_2019.merge(T_sf6_2019, left_on ='Facility Name', right_on='Facility Name') 
#D2020 = T_de_2020.merge(T_sf6_2020, left_on ='Facility Name', right_on='Facility Name')

In [13]:
#D2017

,Facility Name,Total reported direct emissions,CO2 emissions (non-biogenic),Methane (CH4) emissions,Nitrous Oxide (N2O) emissions,HFC emissions,PFC emissions,SF6 emissions _x,NF3 emissions,Other Fully Fluorinated GHG emissions,Very Short-lived Compounds emissions,Other GHGs (metric tons CO2e),Biogenic CO2 emissions (metric tons),SF6 emissions _y
0,BP Whiting Business Unit,"4,722,108.68","4,693,682.20","17,666.00","10,760.48",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,579.12
1,Coalinga Cogeneration Facility,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DOW TEXAS OPERATIONS FREEPORT,"3,891,696.37","3,770,026.90","119,177.00","2,492.47",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,643.88"
3,Gibbons Creek Steam Electric Station,"1,742,308.64","1,728,303.70","5,122.75","8,882.19",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"5,016.00"
4,Kern River Cogeneration Facility,"461,822.91","461,346.70",217.25,258.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.52
5,Muscatine,"1,166,615.61","1,158,229.80","3,068.00","5,317.81",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.12
6,Red Gate Power Plant,"106,550.00","106,440.40",50,59.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,SYCAMORE COGENERATION Facility,"829,188.68","828,333.80",390,464.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,253.08
8,Salinas River Cogeneration Facility,"66,697.65","66,629.70",31,36.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Sargent Canyon Cogeneration Facility,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
F2017 = T_de_2017.merge(T_2017, left_on ='Facility Name', right_on='FACILITY NAME') 
F2018 = T_de_2018.merge(T_2018, left_on ='Facility Name', right_on='FACILITY NAME') 
F2019 = T_de_2019.merge(T_2019, left_on ='Facility Name', right_on='FACILITY NAME') 
F2020 = T_de_2020.merge(T_2020, left_on ='Facility Name', right_on='FACILITY NAME')

In [45]:
F2017

,Facility Name,Total reported direct emissions,CO2 emissions (non-biogenic),Methane (CH4) emissions,Nitrous Oxide (N2O) emissions,HFC emissions,PFC emissions,SF6 emissions,NF3 emissions,Other Fully Fluorinated GHG emissions,Very Short-lived Compounds emissions,Other GHGs (metric tons CO2e),Biogenic CO2 emissions (metric tons),FACILITY NAME,PARENT COMPANY NAME,FACILITY NAICS CODE
0,121 REGIONAL DISPOSAL FACILITY,"250,497.50",NaN,"250,497.50",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121 REGIONAL DISPOSAL FACILITY,NORTH TEXAS MUNICIPAL WATER DISTRICT,562212.0
1,15-18565/15-18662,"218,699.25",NaN,"218,699.25",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15-18565/15-18662,CAMBRIAN COAL LLC,212112.0
2,15-19015,"70,265.00",NaN,"70,265.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15-19015,CAMBRIAN COAL LLC,212112.0
3,17Z Gas Plant - Chevron USA Inc.,"9,298.92","9,120.10",173.75,5.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17Z Gas Plant - Chevron USA Inc.,CHEVRON CORP,211130.0
4,23rd and 3rd,"52,698.66","52,645.50",24.25,28.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23rd and 3rd,NEW YORK POWER AUTHORITY,221112.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7750,Zider,"11,961.96","11,940.40",15,6.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zider,ENBRIDGE ENERGY MANAGEMENT,486210.0
7751,Zion Energy Center,"271,470.88","271,218.80",115,137.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zion Energy Center,CALPINE CORP,221112.0
7752,Zuni,"14,363.20","14,348.40",6.75,8.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zuni,XCEL ENERGY,221330.0
7753,voestalpine Texas LLC,"749,328.25","749,301.40",12.25,14.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,voestalpine Texas LLC,VOESTALPINE TEXAS LLC,331111.0
7754,white oak landfill,"66,643.35",1.1,"66,642.25",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,white oak landfill,HAYWOOD COUNTY NORTH CAROLINA,562212.0

In [46]:
#drop extra name
F12017 = F2017.drop(columns=['Facility Name'])
F12018 = F2018.drop(columns=['Facility Name'])
F12019 = F2019.drop(columns=['Facility Name'])
F12020 = F2020.drop(columns=['Facility Name'])

In [29]:

''' 
#drop null is all 0 are there
#if there is a null in the row

data = F12017;
count = 0;

def Tidy(data):
    for row in data.rows:
        for item in row:
            if item == null:
                count == count + 1;
            return item;
            
            
'''   

''' 
Tidy(F12017)
Tidy(F12018)
Tidy(F12019)
Tidy(F12020)
'''

' \nTidy(F12017)\nTidy(F12018)\nTidy(F12019)\nTidy(F12020)\n'

In [30]:
'''
F120171 = F12017.dropna(axis=0, how='all', thresh=None, subset= ["Total reported direct emissions", "CO2 emissions (non-biogenic) ", "Methane (CH4) emissions ", "Nitrous Oxide (N2O) emissions ", "HFC emissions", "PFC emissions", "NF3 emissions", "Other Fully Fluorinated GHG emissions", "Very Short-lived Compounds emissions", "Other GHGs (metric tons CO2e)", "Biogenic CO2 emissions (metric tons)"], inplace=False)
'''

'\nF120171 = F12017.dropna(axis=0, how=\'all\', thresh=None, subset= ["Total reported direct emissions", "CO2 emissions (non-biogenic) ", "Methane (CH4) emissions ", "Nitrous Oxide (N2O) emissions ", "HFC emissions", "PFC emissions", "NF3 emissions", "Other Fully Fluorinated GHG emissions", "Very Short-lived Compounds emissions", "Other GHGs (metric tons CO2e)", "Biogenic CO2 emissions (metric tons)"], inplace=False)\n'

In [47]:
#replace na with 0
F122017 = F12017.fillna(0)
F122018 = F12018.fillna(0)
F122019 = F12019.fillna(0)
F122020 = F12020.fillna(0)

In [48]:
F122017

,Total reported direct emissions,CO2 emissions (non-biogenic),Methane (CH4) emissions,Nitrous Oxide (N2O) emissions,HFC emissions,PFC emissions,SF6 emissions,NF3 emissions,Other Fully Fluorinated GHG emissions,Very Short-lived Compounds emissions,Other GHGs (metric tons CO2e),Biogenic CO2 emissions (metric tons),FACILITY NAME,PARENT COMPANY NAME,FACILITY NAICS CODE
0,"250,497.50",0,"250,497.50",0,0,0,0,0,0,0,0,0,121 REGIONAL DISPOSAL FACILITY,NORTH TEXAS MUNICIPAL WATER DISTRICT,562212.0
1,"218,699.25",0,"218,699.25",0,0,0,0,0,0,0,0,0,15-18565/15-18662,CAMBRIAN COAL LLC,212112.0
2,"70,265.00",0,"70,265.00",0,0,0,0,0,0,0,0,0,15-19015,CAMBRIAN COAL LLC,212112.0
3,"9,298.92","9,120.10",173.75,5.07,0,0,0,0,0,0,0,0,17Z Gas Plant - Chevron USA Inc.,CHEVRON CORP,211130.0
4,"52,698.66","52,645.50",24.25,28.91,0,0,0,0,0,0,0,0,23rd and 3rd,NEW YORK POWER AUTHORITY,221112.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7750,"11,961.96","11,940.40",15,6.56,0,0,0,0,0,0,0,0,Zider,ENBRIDGE ENERGY MANAGEMENT,486210.0
7751,"271,470.88","271,218.80",115,137.08,0,0,0,0,0,0,0,0,Zion Energy Center,CALPINE CORP,221112.0
7752,"14,363.20","14,348.40",6.75,8.05,0,0,0,0,0,0,0,0,Zuni,XCEL ENERGY,221330.0
7753,"749,328.25","749,301.40",12.25,14.6,0,0,0,0,0,0,0,0,voestalpine Texas LLC,VOESTALPINE TEXAS LLC,331111.0
7754,"66,643.35",1.1,"66,642.25",0,0,0,0,0,0,0,0,0,white oak landfill,HAYWOOD COUNTY NORTH CAROLINA,562212.0

In [49]:
F122018

,Total reported direct emissions,CO2 emissions (non-biogenic),Methane (CH4) emissions,Nitrous Oxide (N2O) emissions,HFC emissions,PFC emissions,SF6 emissions,NF3 emissions,Other Fully Fluorinated GHG emissions,Very Short-lived Compounds emissions,Other GHGs (metric tons CO2e),Biogenic CO2 emissions (metric tons),FACILITY NAME,PARENT COMPANY NAME,FACILITY NAICS CODE
0,"653,854.00",0,"653,854.00",0,0,0,0,0,0,0.0,0,0,121 REGIONAL DISPOSAL FACILITY,NORTH TEXAS MUNICIPAL WATER DISTRICT,562212.0
1,"125,981.75",0,"125,981.75",0,0,0,0,0,0,0.0,0,0,15-18565/15-18662,CAMBRIAN COAL LLC,212112.0
2,"93,918.75",0,"93,918.75",0,0,0,0,0,0,0.0,0,0,15-19015,CAMBRIAN COAL LLC,212112.0
3,"3,564.14","3,485.60",76.75,1.79,0,0,0,0,0,0.0,0,0,17Z Gas Plant - Chevron USA Inc.,CHEVRON CORP,211130.0
4,"70,705.29","70,633.50",32.75,39.04,0,0,0,0,0,0.0,0,0,23rd and 3rd,NEW YORK POWER AUTHORITY,221112.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7821,"30,924.15","30,908.60",7.5,8.05,0,0,0,0,0,0.0,0,0,Zider,MIDCOAST ENERGY LLC,486210.0
7822,"321,472.99","321,142.40",150,180.59,0,0,0,0,0,0.0,0,0,Zion Energy Center,CALPINE CORP,221112.0
7823,"16,707.79","16,690.80",7.75,9.24,0,0,0,0,0,0.0,0,0,Zuni,XCEL ENERGY,221330.0
7824,"783,385.60","783,359.30",12,14.3,0,0,0,0,0,0.0,0,0,voestalpine Texas LLC,VOESTALPINE TEXAS LLC,331110.0
7825,"74,998.25",0.5,"74,997.75",0,0,0,0,0,0,0.0,0,0,white oak landfill,HAYWOOD COUNTY NORTH CAROLINA,562212.0

In [50]:
F122019

,Total reported direct emissions,CO2 emissions (non-biogenic),Methane (CH4) emissions,Nitrous Oxide (N2O) emissions,HFC emissions,PFC emissions,SF6 emissions,NF3 emissions,Other Fully Fluorinated GHG emissions,Very Short-lived Compounds emissions,Other GHGs (metric tons CO2e),Biogenic CO2 emissions (metric tons),FACILITY NAME,PARENT COMPANY NAME,FACILITY NAICS CODE
0,"518,680.25",0,"518,680.25",0,0,0,0,0,0,0.0,0,0,121 REGIONAL DISPOSAL FACILITY,NORTH TEXAS MUNICIPAL WATER DISTRICT,562212
1,"44,658.38","44,612.90",20.75,24.73,0,0,0,0,0,0.0,0,0,23rd and 3rd,NEW YORK POWER AUTHORITY,221112
2,"38,691.48","36,963.80","1,709.50",18.18,0,0,0,0,0,0.0,0,0,3Bear Libby Gas Plant,3 Bear Delaware Operating â€“ NM LLC,211130
3,"18,925.40",246.9,"18,678.50",0,0,0,0,0,0,0.0,0,0,31st Street Landfill,ARCHDIOCESE OF CHICAGO,562212
4,"30,571.64","30,540.40",14.25,16.99,0,0,0,0,0,0.0,0,0,3M BROWNWOOD,3M CO,326113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7699,"44,919.95","44,858.40",53.5,8.05,0,0,0,0,0,0.0,0,0,Zider,MIDCOAST ENERGY LLC,486210
7700,"395,152.49","394,751.60",182.75,218.14,0,0,0,0,0,0.0,0,0,Zion Energy Center,VOLT PARENT LP,221112
7701,"10,870.86","10,859.90",5,5.96,0,0,0,0,0,0.0,0,0,Zuni,XCEL ENERGY,221330
7702,"857,709.82","857,686.80",10.5,12.52,0,0,0,0,0,0.0,0,0,voestalpine Texas LLC,VOESTALPINE TEXAS LLC,331110
7703,"82,134.75",0,"82,134.75",0,0,0,0,0,0,0.0,0,0,white oak landfill,COUNTY OF HAYWOOD,562212

In [51]:
F122020

,Total reported direct emissions,CO2 emissions (non-biogenic),Methane (CH4) emissions,Nitrous Oxide (N2O) emissions,HFC emissions,PFC emissions,SF6 emissions,NF3 emissions,Other Fully Fluorinated GHG emissions,Very Short-lived Compounds emissions,Other GHGs (metric tons CO2e),Biogenic CO2 emissions (metric tons),FACILITY NAME,PARENT COMPANY NAME,FACILITY NAICS CODE
0,"504,064.00",0,"504,064.00",0,0,0,0,0,0,0.0,0,0,121 REGIONAL DISPOSAL FACILITY,NORTH TEXAS MUNICIPAL WATER DISTRICT,562212.0
1,"60,819.70","60,751.20",31.25,37.25,0,0,0,0,0,0.0,0,0,23rd and 3rd,NEW YORK POWER AUTHORITY,221112.0
2,"40,521.81","39,555.50",945.75,20.56,0,0,0,0,0,0.0,0,0,3Bear Libby Gas Plant,3 BEAR DELAWARE OPERATING â€“ NM LLC,211130.0
3,"100,500.95",334.9,"100,165.75",0.3,0,0,0,0,0,0.0,0,0,31st Street Landfill,CATHOLIC BISHOP OF CHICAGO,562212.0
4,"29,359.64","29,329.50",13.75,16.39,0,0,0,0,0,0.0,0,0,3M BROWNWOOD,3M CO,326113.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7583,"22,359.12","22,350.20",4.75,4.17,0,0,0,0,0,0.0,0,0,Zider,MIDCOAST ENERGY LLC,486210.0
7584,"325,679.42","325,344.10",151.75,183.57,0,0,0,0,0,0.0,0,0,Zion Energy Center,VOLT PARENT LP,221112.0
7585,0,0,0,0,0,0,0,0,0,0.0,0,0,Zuni,XCEL ENERGY INC,221330.0
7586,"650,907.10","650,879.70",12.5,14.9,0,0,0,0,0,0.0,0,0,voestalpine Texas LLC,VOESTALPINE TEXAS LLC,331110.0
7587,"89,476.75",0,"89,476.75",0,0,0,0,0,0,0.0,0,0,white oak landfill,COUNTY OF HAYWOOD,562212.0

In [ ]:
#based off of potency 
#CO2
#Methane
#Nitros