In [229]:
import pandas as pd 
import numpy as np

import datetime
from datetime import date
from dateutil.relativedelta import relativedelta


length_of_timeframe = 5  #CHANGE BACK TO 1 IF FAILS
#5 years is the maximum available from Tiingo


today = date.today() - datetime.timedelta(days = 3) ##Delete the relativedelta subtraction when done
end = today.strftime("%Y-%m-%d") #Today's date in YYYY-MM-DD format

today = today - relativedelta(years=length_of_timeframe)
start = today.strftime("%Y-%m-%d") #Date that is 5 years before

In [194]:
#CSV Citation: https://datahub.io/core/s-and-p-500-companies-financials#data

SP500_extract = pd.read_csv('/Users/kaylie/Downloads/SP500_Ticker_List.csv')

SP500_Company_Names = SP500_extract['Description']
SP500_Company_Names = SP500_Company_Names.astype(str)
SP500_Company_Names = SP500_Company_Names.to_numpy()

SP500_Tickers = SP500_extract['Symbol']
SP500_Tickers = SP500_Tickers.astype(str)
SP500_Tickers = SP500_Tickers.to_numpy()
SP500_Tickers = SP500_Tickers.tolist()

In [195]:
import multiprocessing as mp
from multiprocessing import pool
import time

import import_ipynb

from ipynb.fs.full.Tiingo_Retrieval_Function import *

split_arrays_of_tickers = np.array_split(SP500_Tickers, 24)

reformatted_splits = []
for list in split_arrays_of_tickers:
    newly_formatted = list.tolist()
    reformatted_splits.append(newly_formatted)


start_time = time.time()
stock_price_data = pd.DataFrame()

for i in range(1,5):
    pool_main = mp.Pool(processes = 6)
    extracted_data = []
    arguments = []
    
    for a in range (6*(i-1), 6*i):
        sub_argument = (start, end, reformatted_splits[a])
        arguments.append(sub_argument)
        
    extracted_data = pool_main.starmap(extract_hourly_timeseries_price_data, arguments)
       
    for a in range(0, 6):
        df1 = extracted_data[a]
        stock_price_data = pd.concat([df1, stock_price_data], axis=1)
    
total_execution_time = (time.time() - start_time)

print(total_execution_time)

153.69954681396484

In [220]:
stock_price_data[:]['WYNN']

2017-09-29 14:00:00+00:00    149.080
2017-09-29 15:00:00+00:00    149.880
2017-09-29 16:00:00+00:00    149.800
2017-09-29 17:00:00+00:00    149.990
2017-09-29 18:00:00+00:00    149.400
                              ...
2022-09-29 16:00:00+00:00     64.530
2022-09-29 17:00:00+00:00     63.555
2022-09-29 18:00:00+00:00     63.520
2022-09-29 19:00:00+00:00     64.345
2022-09-29 20:00:00+00:00        NaN
Name: WYNN, Length: 9135, dtype: float64

In [218]:
stock_price_data

,WYNN,FRT,FBHS,TPR,CZR,PNR,SEE,IVZ,XRAY,AOS,...,WMT,LLY,JPM,PG,NVDA,V,HD,CVX,MA,ABBV
2017-09-29 14:00:00+00:00,149.080,124.530,67.245,NaN,25.550,68.250,42.595,35.015,59.230,59.295,...,78.625,84.985,95.085,90.930,178.240,105.040,162.560,117.050,141.310,89.010
2017-09-29 15:00:00+00:00,149.880,124.310,67.100,NaN,25.625,68.095,42.595,34.980,59.450,59.290,...,78.800,85.020,95.280,91.025,178.240,105.010,163.355,116.900,141.370,88.920
2017-09-29 16:00:00+00:00,149.800,123.990,67.300,NaN,25.775,68.110,42.670,34.970,59.700,59.320,...,78.560,85.090,95.345,90.975,179.350,105.070,163.295,117.320,141.170,88.980
2017-09-29 17:00:00+00:00,149.990,123.860,67.250,NaN,25.725,67.970,42.640,34.900,59.710,59.340,...,78.430,85.360,95.330,90.935,178.890,104.885,163.395,117.190,141.300,88.710
2017-09-29 18:00:00+00:00,149.400,123.860,67.010,NaN,25.925,67.950,42.725,34.900,59.620,59.365,...,78.460,85.205,95.430,90.915,178.460,105.150,163.355,117.300,141.115,88.870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-09-29 16:00:00+00:00,64.530,88.860,54.795,28.810,31.865,40.715,43.960,14.135,29.315,48.890,...,132.680,330.185,106.030,129.770,121.180,180.455,277.500,144.595,288.020,142.885
2022-09-29 17:00:00+00:00,63.555,88.455,54.400,28.560,31.545,40.780,43.945,14.025,29.035,48.635,...,132.015,329.205,105.530,128.800,120.045,179.280,275.145,144.105,285.580,142.380
2022-09-29 18:00:00+00:00,63.520,88.230,54.370,28.670,31.885,40.695,44.315,14.020,29.015,48.600,...,131.960,327.555,105.550,128.560,120.165,178.980,275.520,143.835,284.890,141.855
2022-09-29 19:00:00+00:00,64.345,88.790,54.530,28.895,32.465,40.965,44.440,14.165,29.155,48.725,...,132.350,330.000,106.100,128.655,122.190,180.310,278.330,144.875,286.870,142.705
2022-09-29 20:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [214]:
data = ['NDAQ', '2022-08-29', 3/1], ['GOOG', '2022-07-18', 20/1], ['GOOGL', '2022-07-18', 20/1], ['TSLA', '2022-08-25', 3/1], ['AMZN', '2022-06-06', 20/1], ['AAPL', '2020-08-31', 4/1], ['TSLA', '2020-08-31', 5/1], ['NVDA', '2021-07-20', 4/1],['VFC', '2019-05-23', 1062/1000], ['PFE', '2020-11-17', 1054/1000], ['MRK', '2021-06-03', 1048/1000],['T', '2022-04-11', 1324/1000], ['NEE', '2020-10-27', 4/1], ['RTX', '2020-04-03', 15890/10000],['HON', '2018-10-01', 1011/1000], ['HON', '2018-10-29', 1032/1000], ['IBM', '2021-11-04', 1046/1000],['TJX', '2018-11-07', 2/1], ['CSX', '2021-06-29', 3/1], ['BDX', '2022-04-01', 1025/1000], ['SHW', '2021-04-01', 3/1], ['FISV', '2018-03-20', 2/1], ['CNC', '2019-02-07', 2/1], ['EXC', '2022-02-02', 1402/1000], ['APH', '2021-03-05', 2/1], ['O', '2021-11-15', 1032/1000], ['MCHP', '2021-10-13', 2/1], ['AFL', '2018-03-19', 2/1], ['DD', '2019-06-03', 4725/10000],['FAST', '2019-05-23', 2/1], ['DTE', '2021-07-01', 1175/1000], ['ZBH', '2022-03-01', 103/100], ['ANET', '2021-11-18', 4/1], ['MKC', '2020-12-01', 2/1], ['ODFL', '2020-03-25', 3/2], ['FTV', '2020-10-09', 1195/1000], ['MTCH', '2020-07-01', 3502/1000], ['LEN', '2017-11-09', 1017/1000],['IP', '2021-10-01', 1056/1000], ['DOV', '2018-05-09', 1238/1000], ['RJF', '2021-09-22', 3/2],['FMC', '2019-03-04', 1153/1000], ['WRB', '2019-04-03', 3/2], ['WRB', '2022-03-24', 3/2],['BRO', '2018-03-29', 2/1], ['HSIC', '2019-02-08', 1275/1000], ['BF.B', '2018-03-01', 5/4], ['BBWI', '2021-08-03', 1237/1000],['PNR', '2018-05-01', 1489/1000], ['DXC', '2018-06-01', 1156/1000],['ROL', '2018-12-11', 3/2], ['ROL', '2020-12-11', 3/2], ['GE', '2019-02-26', 104/100],['GE', '2021-08-02', 1/8], ['ISRG', '2017-10-06', 3/1], ['ISRG', '2021-10-05', 3/1]

stock_splits = pd.DataFrame(data, columns = ['Ticker', 'Date', 'Adjustment Factor'])

In [215]:
stock_price_data.index = pd.to_datetime(stock_price_data.index)
pd.options.mode.chained_assignment = None #False positive SettingWithCopyWarning

In [216]:
for a in range(len(stock_splits)):
    date = stock_splits['Date'][a]   
    stock_price_data.loc[:date][stock_splits['Ticker'][a]] = stock_price_data.loc[:date][stock_splits['Ticker'][a]]/(stock_splits['Adjustment Factor'][a])
    stock_price_data.loc[date][stock_splits['Ticker'][a]] = stock_price_data.loc[date][stock_splits['Ticker'][a]]*(stock_splits['Adjustment Factor'][a])

,WYNN,FRT,FBHS,TPR,CZR,PNR,SEE,IVZ,XRAY,AOS,...,WMT,LLY,JPM,PG,NVDA,V,HD,CVX,MA,ABBV
2017-09-29 14:00:00+00:00,149.080,124.530,67.245,NaN,25.550,68.250,42.595,35.015,59.230,59.295,...,78.625,84.985,95.085,90.930,178.240,105.040,162.560,117.050,141.310,89.010
2017-09-29 15:00:00+00:00,149.880,124.310,67.100,NaN,25.625,68.095,42.595,34.980,59.450,59.290,...,78.800,85.020,95.280,91.025,178.240,105.010,163.355,116.900,141.370,88.920
2017-09-29 16:00:00+00:00,149.800,123.990,67.300,NaN,25.775,68.110,42.670,34.970,59.700,59.320,...,78.560,85.090,95.345,90.975,179.350,105.070,163.295,117.320,141.170,88.980
2017-09-29 17:00:00+00:00,149.990,123.860,67.250,NaN,25.725,67.970,42.640,34.900,59.710,59.340,...,78.430,85.360,95.330,90.935,178.890,104.885,163.395,117.190,141.300,88.710
2017-09-29 18:00:00+00:00,149.400,123.860,67.010,NaN,25.925,67.950,42.725,34.900,59.620,59.365,...,78.460,85.205,95.430,90.915,178.460,105.150,163.355,117.300,141.115,88.870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-09-29 16:00:00+00:00,64.530,88.860,54.795,28.810,31.865,40.715,43.960,14.135,29.315,48.890,...,132.680,330.185,106.030,129.770,121.180,180.455,277.500,144.595,288.020,142.885
2022-09-29 17:00:00+00:00,63.555,88.455,54.400,28.560,31.545,40.780,43.945,14.025,29.035,48.635,...,132.015,329.205,105.530,128.800,120.045,179.280,275.145,144.105,285.580,142.380
2022-09-29 18:00:00+00:00,63.520,88.230,54.370,28.670,31.885,40.695,44.315,14.020,29.015,48.600,...,131.960,327.555,105.550,128.560,120.165,178.980,275.520,143.835,284.890,141.855
2022-09-29 19:00:00+00:00,64.345,88.790,54.530,28.895,32.465,40.965,44.440,14.165,29.155,48.725,...,132.350,330.000,106.100,128.655,122.190,180.310,278.330,144.875,286.870,142.705
2022-09-29 20:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN